openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    API для керування контактами (створення, редагування, видалення, отримання).
tags:
  - name: Contacts
    description: Все про контакти
  - name: Auth
    description: Авторизація користувача
servers:
  - url: http://localhost:3000
  - url: https://<твоє-посилання-на-render>
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    $ref: ../swagger/paths/auth/reset-pwd.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: ../swagger/components/Contact.yaml#/schemas/Contact
    CreateContactInput:
      $ref: ../swagger/components/Contact.yaml#/schemas/CreateContactInput
    UpdateContactInput:
      $ref: ../swagger/components/Contact.yaml#/schemas/UpdateContactInput
    RegisterInput:
      $ref: ../swagger/components/Auth.yaml#/schemas/RegisterInput
    LoginInput:
      $ref: ../swagger/components/Auth.yaml#/schemas/LoginInput
    ResetEmailInput:
      $ref: ../swagger/components/Auth.yaml#/schemas/ResetEmailInput
    ResetPwdInput:
      $ref: ../swagger/components/Auth.yaml#/schemas/ResetPwdInput
